In [1]:
import HEAD_RECON
import multi_head
import copy
import numpy as np
import matplotlib.pyplot as plt
import cv2
from scipy.ndimage.morphology import binary_fill_holes
import sys
np.set_printoptions(threshold=sys.maxsize)

%load_ext autoreload
%autoreload 2

<IPython.core.display.Javascript object>

In [8]:
# gen 2d images
for i in range(1,2):
    print(i)
    head = HEAD_RECON.threeD_head.read_from_file(1,i)
    head.reset_filters()
    head.filter_nan()
    head.filter_depth(1.5)
    head.sparsify(1)
    head.parzen_filter(p=20,r=0.01)
    print("dangling removal done")
#     head.remove_background_color()
    print("color filter done.")
#     head.edge_based_filter()
#     head.erode_filter(5)
#     head.filter_depth(1.5)
#     head.remove_dangling()
    head.center()
    head.get_filtered_image()
    head.create_vpython_spheres()
    head.save()

1
0 53999
1 53999
2 53999
3 53999
4 53999
5 53999
6 53999
7 53999
8 53999
9 53999
10 53999
11 53999
12 53999
13 53999
14 53999
15 53999
18 53999
19 53999
26 53999
27 53999
29 53999
30 53999
34 53999
35 53999
36 53999
37 53999
38 53999
39 53999
40 53999
41 53999
42 53999
43 53999
44 53999
45 53999
46 53999
47 53999
48 53999
49 53999
50 53999
51 53999
60 53999
61 53999
65 53999
66 53999
70 53999
71 53999
79 53999
80 53999
81 53999
82 53999
83 53999
84 53999
85 53999
86 53999
87 53999
88 53999
89 53999
91 53999
92 53999
93 53999
94 53999
95 53999
134 53999
135 53999
137 53999
138 53999
144 53999
145 53999
172 53999
173 53999
188 53999
189 53999
190 53999
191 53999
192 53999
196 53999
197 53999
198 53999
199 53999
200 53999
253 53999
254 53999
259 53999
260 53999
317 53999
318 53999
319 53999
320 53999
326 53999
327 53999
328 53999
329 53999
390 53999
391 53999
392 53999
393 53999
394 53999
465 53999
466 53999
541 53999
542 53999
543 53999
544 53999
621 53999
622 53999
623 53999
701 53999


30417 53999
30418 53999
30419 53999
30698 53999
30699 53999
30978 53999
30979 53999
31258 53999
31259 53999
31538 53999
31539 53999
31818 53999
31819 53999
31820 53999
32101 53999
32102 53999
32383 53999
32384 53999
32385 53999
32668 53999
32669 53999
32670 53999
32671 53999
32672 53999
32957 53999
33242 53999
33243 53999
33244 53999
33530 53999
33816 53999
33817 53999
33818 53999
34104 53999
34105 53999
34392 53999
34393 53999
34394 53999
34683 53999
34684 53999
34975 53999
34976 53999
35267 53999
35268 53999
35559 53999
35560 53999
35851 53999
36143 53999
36144 53999
36145 53999
36438 53999
36439 53999
36733 53999
36734 53999
36735 53999
36736 53999
37032 53999
37033 53999
37034 53999
37332 53999
37333 53999
37632 53999
37633 53999
37933 53999
37934 53999
37935 53999
37936 53999
37937 53999
38237 53999
38238 53999
38538 53999
38539 53999
38675 53999
38676 53999
38677 53999
38839 53999
38840 53999
38976 53999
39138 53999
39139 53999
39140 53999
39276 53999
39277 53999
39278 53999
3944

10446 53863
10447 53863
10565 53863
10566 53863
10683 53863
10684 53863
10685 53863
10800 53863
10801 53863
10914 53863
10915 53863
11028 53863
11029 53863
11141 53863
11142 53863
11253 53863
11254 53863
11363 53863
11364 53863
11472 53863
11473 53863
11579 53863
11580 53863
11581 53863
11685 53863
11686 53863
11687 53863
11790 53863
11791 53863
11891 53863
11892 53863
11893 53863
11992 53863
11993 53863
12092 53863
12093 53863
12192 53863
12193 53863
12291 53863
12292 53863
12293 53863
12294 53863
12295 53863
12298 53863
12299 53863
12300 53863
12391 53863
12392 53863
12393 53863
12394 53863
12484 53863
12485 53863
12486 53863
12487 53863
12488 53863
12576 53863
12577 53863
12578 53863
12579 53863
12580 53863
12663 53863
12664 53863
12746 53863
12747 53863
12828 53863
12829 53863
12830 53863
12909 53863
12910 53863
12989 53863
12990 53863
12991 53863
13068 53863
13069 53863
13070 53863
13071 53863
13072 53863
13147 53863
13148 53863
13223 53863
13224 53863
13299 53863
13300 53863
1337

53765 53863
53766 53863
53767 53863
53768 53863
53769 53863
53770 53863
53771 53863
53772 53863
53773 53863
53774 53863
53775 53863
53776 53863
53777 53863
53778 53863
53779 53863
53780 53863
53781 53863
53782 53863
53783 53863
53784 53863
53785 53863
53786 53863
53787 53863
53788 53863
53789 53863
53790 53863
53791 53863
53792 53863
53793 53863
53794 53863
53795 53863
53796 53863
53797 53863
53798 53863
53799 53863
53800 53863
53801 53863
53802 53863
53803 53863
53804 53863
53805 53863
53806 53863
53807 53863
53808 53863
53809 53863
53810 53863
53811 53863
53812 53863
53813 53863
53814 53863
53815 53863
53816 53863
53817 53863
53818 53863
53819 53863
53820 53863
53821 53863
53822 53863
53823 53863
53824 53863
53825 53863
53826 53863
53827 53863
53828 53863
53829 53863
53830 53863
53831 53863
53832 53863
53833 53863
53834 53863
53835 53863
53836 53863
53837 53863
53838 53863
53839 53863
53840 53863
53841 53863
53842 53863
53843 53863
53844 53863
53845 53863
53846 53863
53847 53863
5384

23875 53760
23876 53760
24140 53760
24141 53760
24406 53760
24407 53760
24408 53760
24674 53760
24675 53760
24676 53760
24944 53760
24945 53760
24946 53760
25217 53760
25218 53760
25489 53760
25490 53760
25491 53760
25492 53760
25493 53760
25494 53760
25767 53760
25768 53760
25769 53760
26047 53760
26048 53760
26327 53760
26328 53760
26329 53760
26609 53760
26610 53760
26890 53760
26891 53760
26892 53760
27171 53760
27172 53760
27173 53760
27174 53760
27450 53760
27451 53760
27452 53760
27453 53760
27729 53760
27730 53760
27887 53760
27888 53760
28004 53760
28005 53760
28161 53760
28162 53760
28278 53760
28279 53760
28552 53760
28553 53760
28827 53760
28828 53760
28829 53760
29103 53760
29104 53760
29378 53760
29379 53760
29653 53760
29654 53760
29929 53760
29930 53760
30206 53760
30207 53760
30208 53760
30485 53760
30486 53760
30763 53760
30764 53760
31041 53760
31042 53760
31319 53760
31320 53760
31597 53760
31598 53760
31599 53760
31878 53760
31879 53760
32158 53760
32159 53760
3216

2750 53668
2751 53668
2752 53668
2753 53668
2754 53668
2756 53668
2757 53668
2868 53668
2869 53668
2870 53668
2871 53668
2872 53668
2982 53668
2983 53668
2984 53668
3093 53668
3094 53668
3095 53668
3205 53668
3206 53668
3317 53668
3318 53668
3430 53668
3431 53668
3432 53668
3433 53668
3547 53668
3548 53668
3663 53668
3664 53668
3779 53668
3780 53668
3895 53668
3896 53668
4011 53668
4012 53668
4127 53668
4128 53668
4243 53668
4244 53668
4359 53668
4360 53668
4476 53668
4477 53668
4593 53668
4594 53668
4710 53668
4711 53668
4827 53668
4828 53668
4943 53668
4944 53668
5059 53668
5060 53668
5176 53668
5177 53668
5293 53668
5294 53668
5410 53668
5411 53668
5527 53668
5528 53668
5644 53668
5645 53668
5762 53668
5763 53668
5880 53668
5881 53668
5998 53668
5999 53668
6116 53668
6117 53668
6234 53668
6235 53668
6352 53668
6353 53668
6470 53668
6471 53668
6589 53668
6590 53668
6591 53668
6708 53668
6709 53668
6825 53668
6826 53668
6827 53668
6828 53668
6829 53668
6830 53668
6946 53668
6947 53668

52471 53668
52472 53668
52801 53668
52802 53668
52803 53668
53134 53668
53135 53668
53136 53668
53137 53668
53138 53668
53139 53668
53140 53668
53141 53668
53142 53668
53143 53668
53144 53668
53145 53668
53146 53668
53147 53668
53148 53668
53149 53668
53150 53668
53151 53668
53152 53668
53153 53668
53154 53668
53155 53668
53156 53668
53157 53668
53158 53668
53159 53668
53160 53668
53161 53668
53162 53668
53163 53668
53164 53668
53165 53668
53166 53668
53167 53668
53168 53668
53169 53668
53170 53668
53171 53668
53172 53668
53173 53668
53174 53668
53175 53668
53176 53668
53177 53668
53178 53668
53254 53668
53255 53668
53256 53668
53257 53668
53258 53668
53259 53668
53260 53668
53261 53668
53262 53668
53263 53668
53264 53668
53265 53668
53266 53668
53267 53668
53268 53668
53269 53668
53270 53668
53271 53668
53272 53668
53273 53668
53274 53668
53275 53668
53276 53668
53277 53668
53278 53668
53279 53668
53280 53668
53281 53668
53282 53668
53283 53668
53284 53668
53285 53668
53286 53668
5328

14966 53587
14967 53587
14968 53587
14969 53587
14970 53587
14971 53587
14972 53587
14973 53587
15125 53587
15126 53587
15127 53587
15128 53587
15129 53587
15130 53587
15284 53587
15285 53587
15286 53587
15287 53587
15288 53587
15289 53587
15290 53587
15291 53587
15292 53587
15293 53587
15294 53587
15295 53587
15296 53587
15297 53587
15298 53587
15462 53587
15463 53587
15636 53587
15637 53587
15638 53587
15639 53587
15640 53587
15641 53587
15642 53587
15643 53587
15644 53587
15645 53587
15646 53587
15829 53587
15830 53587
15831 53587
15832 53587
15833 53587
15834 53587
15835 53587
15836 53587
15837 53587
15838 53587
16025 53587
16026 53587
16030 53587
16031 53587
16032 53587
16221 53587
16222 53587
16223 53587
16224 53587
16225 53587
16226 53587
16227 53587
16228 53587
16425 53587
16426 53587
16629 53587
16630 53587
16631 53587
16632 53587
16633 53587
16634 53587
16635 53587
16841 53587
16842 53587
16843 53587
16844 53587
16845 53587
16846 53587
16847 53587
16848 53587
17059 53587
1706

0 53511
1 53511
2 53511
3 53511
4 53511
5 53511
6 53511
7 53511
8 53511
9 53511
10 53511
11 53511
12 53511
13 53511
14 53511
15 53511
18 53511
19 53511
26 53511
27 53511
29 53511
30 53511
34 53511
35 53511
36 53511
37 53511
38 53511
39 53511
40 53511
41 53511
42 53511
43 53511
44 53511
45 53511
46 53511
47 53511
48 53511
49 53511
58 53511
59 53511
63 53511
64 53511
68 53511
69 53511
77 53511
78 53511
79 53511
80 53511
81 53511
82 53511
83 53511
84 53511
85 53511
86 53511
87 53511
88 53511
89 53511
90 53511
129 53511
130 53511
136 53511
137 53511
164 53511
165 53511
180 53511
181 53511
182 53511
183 53511
184 53511
185 53511
186 53511
187 53511
188 53511
189 53511
190 53511
191 53511
244 53511
245 53511
250 53511
251 53511
308 53511
309 53511
310 53511
311 53511
317 53511
318 53511
319 53511
320 53511
381 53511
382 53511
383 53511
384 53511
455 53511
456 53511
531 53511
532 53511
533 53511
534 53511
611 53511
612 53511
613 53511
691 53511
692 53511
770 53511
771 53511
772 53511
850 5351

29976 53511
30250 53511
30251 53511
30525 53511
30526 53511
30800 53511
30801 53511
31075 53511
31076 53511
31350 53511
31351 53511
31352 53511
31629 53511
31630 53511
31631 53511
31909 53511
31910 53511
31911 53511
32192 53511
32193 53511
32194 53511
32195 53511
32196 53511
32479 53511
32480 53511
32764 53511
32765 53511
32766 53511
33052 53511
33338 53511
33339 53511
33340 53511
33626 53511
33627 53511
33914 53511
33915 53511
33916 53511
34205 53511
34206 53511
34497 53511
34498 53511
34789 53511
34790 53511
35081 53511
35082 53511
35373 53511
35665 53511
35666 53511
35667 53511
35960 53511
35961 53511
36255 53511
36256 53511
36257 53511
36258 53511
36554 53511
36555 53511
36556 53511
36854 53511
36855 53511
37154 53511
37155 53511
37455 53511
37456 53511
37457 53511
37458 53511
37459 53511
37759 53511
37760 53511
38060 53511
38061 53511
38197 53511
38198 53511
38199 53511
38361 53511
38362 53511
38498 53511
38660 53511
38661 53511
38662 53511
38798 53511
38799 53511
38800 53511
3896

9917 53442
9918 53442
9919 53442
10031 53442
10032 53442
10145 53442
10146 53442
10259 53442
10260 53442
10373 53442
10374 53442
10487 53442
10488 53442
10600 53442
10601 53442
10602 53442
10712 53442
10713 53442
10822 53442
10823 53442
10931 53442
10932 53442
11039 53442
11040 53442
11146 53442
11147 53442
11251 53442
11252 53442
11355 53442
11356 53442
11457 53442
11458 53442
11459 53442
11558 53442
11559 53442
11657 53442
11658 53442
11754 53442
11755 53442
11756 53442
11850 53442
11851 53442
11945 53442
11946 53442
11947 53442
12041 53442
12042 53442
12135 53442
12136 53442
12137 53442
12138 53442
12139 53442
12230 53442
12231 53442
12321 53442
12322 53442
12323 53442
12324 53442
12412 53442
12413 53442
12414 53442
12415 53442
12416 53442
12499 53442
12500 53442
12582 53442
12583 53442
12664 53442
12665 53442
12666 53442
12745 53442
12746 53442
12825 53442
12826 53442
12827 53442
12904 53442
12905 53442
12906 53442
12907 53442
12908 53442
12983 53442
12984 53442
13059 53442
13060 5

53254 53442
53255 53442
53256 53442
53257 53442
53258 53442
53259 53442
53260 53442
53261 53442
53262 53442
53263 53442
53264 53442
53265 53442
53266 53442
53267 53442
53268 53442
53269 53442
53270 53442
53271 53442
53272 53442
53273 53442
53274 53442
53275 53442
53276 53442
53277 53442
53278 53442
53279 53442
53280 53442
53281 53442
53282 53442
53283 53442
53284 53442
53285 53442
53286 53442
53287 53442
53288 53442
53289 53442
53290 53442
53291 53442
53292 53442
53293 53442
53294 53442
53295 53442
53296 53442
53297 53442
53298 53442
53299 53442
53300 53442
53301 53442
53302 53442
53303 53442
53304 53442
53305 53442
53306 53442
53307 53442
53308 53442
53309 53442
53310 53442
53311 53442
53312 53442
53313 53442
53314 53442
53315 53442
53316 53442
53317 53442
53318 53442
53319 53442
53320 53442
53321 53442
53322 53442
53323 53442
53324 53442
53325 53442
53326 53442
53327 53442
53328 53442
53329 53442
53330 53442
53331 53442
53332 53442
53333 53442
53334 53442
53335 53442
53336 53442
5333

19671 53378
19672 53378
19673 53378
19915 53378
19916 53378
20160 53378
20161 53378
20162 53378
20163 53378
20164 53378
20411 53378
20412 53378
20413 53378
20662 53378
20663 53378
20664 53378
20665 53378
20666 53378
20667 53378
20922 53378
20923 53378
20924 53378
21180 53378
21437 53378
21438 53378
21439 53378
21440 53378
21441 53378
21701 53378
21702 53378
21962 53378
21963 53378
22224 53378
22225 53378
22226 53378
22227 53378
22228 53378
22229 53378
22491 53378
22753 53378
22754 53378
22755 53378
23018 53378
23019 53378
23020 53378
23285 53378
23286 53378
23287 53378
23288 53378
23553 53378
23554 53378
23818 53378
23819 53378
24084 53378
24085 53378
24086 53378
24352 53378
24353 53378
24354 53378
24622 53378
24623 53378
24624 53378
24895 53378
24896 53378
25167 53378
25168 53378
25169 53378
25170 53378
25171 53378
25172 53378
25445 53378
25446 53378
25447 53378
25725 53378
25726 53378
26005 53378
26006 53378
26007 53378
26287 53378
26288 53378
26568 53378
26569 53378
26570 53378
2684

850 53324
851 53324
930 53324
931 53324
1011 53324
1012 53324
1013 53324
1014 53324
1015 53324
1016 53324
1100 53324
1101 53324
1186 53324
1187 53324
1188 53324
1189 53324
1190 53324
1191 53324
1192 53324
1283 53324
1284 53324
1285 53324
1378 53324
1379 53324
1380 53324
1381 53324
1477 53324
1478 53324
1479 53324
1576 53324
1577 53324
1676 53324
1677 53324
1678 53324
1779 53324
1780 53324
1882 53324
1883 53324
1985 53324
1986 53324
1987 53324
2090 53324
2091 53324
2196 53324
2197 53324
2198 53324
2199 53324
2306 53324
2307 53324
2415 53324
2416 53324
2417 53324
2524 53324
2525 53324
2633 53324
2634 53324
2635 53324
2636 53324
2637 53324
2746 53324
2747 53324
2748 53324
2749 53324
2750 53324
2752 53324
2753 53324
2864 53324
2865 53324
2866 53324
2867 53324
2868 53324
2978 53324
2979 53324
2980 53324
3089 53324
3090 53324
3091 53324
3201 53324
3202 53324
3313 53324
3314 53324
3426 53324
3427 53324
3428 53324
3429 53324
3543 53324
3544 53324
3659 53324
3660 53324
3775 53324
3776 53324
389

40001 53324
40002 53324
40003 53324
40308 53324
40309 53324
40613 53324
40614 53324
40918 53324
40919 53324
40920 53324
41225 53324
41226 53324
41227 53324
41228 53324
41534 53324
41535 53324
41844 53324
41845 53324
41846 53324
42156 53324
42157 53324
42467 53324
42468 53324
42469 53324
42781 53324
42782 53324
42783 53324
42784 53324
42785 53324
43101 53324
43102 53324
43416 53324
43417 53324
43732 53324
43733 53324
44048 53324
44049 53324
44363 53324
44364 53324
44679 53324
44680 53324
44996 53324
44997 53324
44998 53324
44999 53324
45317 53324
45318 53324
45637 53324
45638 53324
45958 53324
45959 53324
45960 53324
45961 53324
45962 53324
46283 53324
46284 53324
46285 53324
46605 53324
46606 53324
46926 53324
46927 53324
47247 53324
47248 53324
47568 53324
47569 53324
47889 53324
47890 53324
47891 53324
47892 53324
48213 53324
48214 53324
48537 53324
48538 53324
48539 53324
48540 53324
48541 53324
48864 53324
49186 53324
49187 53324
49509 53324
49510 53324
49832 53324
49833 53324
5015

13231 53277
13232 53277
13304 53277
13305 53277
13377 53277
13378 53277
13379 53277
13451 53277
13452 53277
13525 53277
13526 53277
13599 53277
13600 53277
13601 53277
13673 53277
13674 53277
13745 53277
13746 53277
13815 53277
13816 53277
13884 53277
13885 53277
13952 53277
13953 53277
13954 53277
13955 53277
14020 53277
14021 53277
14085 53277
14086 53277
14149 53277
14150 53277
14213 53277
14214 53277
14215 53277
14216 53277
14217 53277
14218 53277
14219 53277
14220 53277
14221 53277
14222 53277
14223 53277
14224 53277
14225 53277
14226 53277
14227 53277
14291 53277
14292 53277
14293 53277
14297 53277
14298 53277
14299 53277
14300 53277
14310 53277
14311 53277
14377 53277
14378 53277
14385 53277
14386 53277
14387 53277
14388 53277
14389 53277
14390 53277
14391 53277
14392 53277
14393 53277
14394 53277
14395 53277
14396 53277
14409 53277
14410 53277
14411 53277
14479 53277
14480 53277
14498 53277
14499 53277
14500 53277
14501 53277
14502 53277
14503 53277
14504 53277
14505 53277
1450

53142 53277
53143 53277
53144 53277
53145 53277
53146 53277
53147 53277
53148 53277
53149 53277
53150 53277
53151 53277
53152 53277
53153 53277
53154 53277
53155 53277
53156 53277
53157 53277
53158 53277
53159 53277
53160 53277
53161 53277
53162 53277
53163 53277
53164 53277
53165 53277
53166 53277
53167 53277
53168 53277
53169 53277
53170 53277
53171 53277
53172 53277
53173 53277
53174 53277
53175 53277
53176 53277
53177 53277
53178 53277
53179 53277
53180 53277
53181 53277
53182 53277
53183 53277
53184 53277
53185 53277
53186 53277
53187 53277
53188 53277
53189 53277
53190 53277
53191 53277
53192 53277
53193 53277
53194 53277
53195 53277
53196 53277
53197 53277
53198 53277
53199 53277
53200 53277
53201 53277
53202 53277
53203 53277
53204 53277
53205 53277
53206 53277
53207 53277
53208 53277
53209 53277
53210 53277
53211 53277
53212 53277
53213 53277
53214 53277
53215 53277
53216 53277
53217 53277
53218 53277
53219 53277
53220 53277
53221 53277
53222 53277
53223 53277
53224 53277
5322

In [2]:
# gen pickled heads
for p in range(2,3):
    for i in range(1,16):
        print(i)
        head = HEAD_RECON.threeD_head.read_from_file(p,i)
        head.full_filter()
        head.get_filtered_image()

1
(307200,)
depth filter done.
dangling removal done
color filter done.
2
(307200,)
depth filter done.
dangling removal done
color filter done.
3
(307200,)
depth filter done.
dangling removal done
color filter done.
4
(307200,)
depth filter done.
dangling removal done
color filter done.
5
(307200,)
depth filter done.
dangling removal done
color filter done.
6
(307200,)
depth filter done.
dangling removal done
color filter done.
7
(307200,)
depth filter done.
dangling removal done
color filter done.
8
(307200,)
depth filter done.
dangling removal done
color filter done.
9
(307200,)
depth filter done.
dangling removal done
color filter done.
10
(307200,)
depth filter done.
dangling removal done
color filter done.
11
(307200,)
depth filter done.
dangling removal done
color filter done.
12
(307200,)
depth filter done.
dangling removal done
color filter done.
13
(307200,)
depth filter done.
dangling removal done
color filter done.
14
(307200,)
depth filter done.
dangling removal done
color 

In [3]:
# load heads
all_heads=[HEAD_RECON.threeD_head.load_from_pickle(4,i) for i in range (1,16)]

In [4]:
def make_mhead(all_heads, first, last):
    all_heads[first].paint([1,0,0])
    all_heads[first].reset_positions()
    all_heads[first].reset_colors()
    all_heads[first+1].reset_positions()
    all_heads[first+1].reset_colors()    
    
    heads = multi_head.MultiHead.joined_heads(all_heads[first], all_heads[first+1])
#     heads.icp_transform(0,1)
    for i in range(first+2,last+1):
        all_heads[i].reset_positions()
        all_heads[i].reset_colors()  
        print (i)
        heads.append_head(all_heads[i])
        heads.join_heads_wraper(i-1-first,i-first)
#         heads.icp_transform(i-1-first,i-first)
    heads.save(sparcity=1) 
    print ("completed")
    return heads

In [5]:
heads = make_mhead(all_heads,0,14)

463



2


363




0 min_error True params: [ 0.02 14.    0.5 ]
363



3


230




0 min_error True params: [ 0.02 14.    0.5 ]
230



4


160


/Users/caseliang/Repositories/AV_CW/SIFT.py:62: RuntimeWarning: divide by zero encountered in double_scalars
  err = np.sqrt(np.var(dist) / (np.sum(inliers) - min_num_inliers))




0 min_error True params: [ 0.02 14.    0.5 ]
160



5


201




0 min_error True params: [ 0.02 14.    0.5 ]
201



6


207




0 min_error True params: [ 0.02 14.    0.5 ]
207



7


161




0 min_error True params: [ 0.02 14.    0.5 ]
161



8


111




0 min_error True params: [ 0.02 14.    0.5 ]
111



9


135




0 min_error True params: [ 0.02 14.    0.5 ]
135



10


106




0 min_error True params: [ 0.02 14.    0.5 ]
106



11


166




0 min_error True params: [ 0.02 14.    0.5 ]
166



12


204




0 min_error True params: [ 0.02 14.    0.5 ]
204



13


167




0 min_error True params: [ 0.02 14.    0.5 ]
167



14


301




0 min_error True params: [ 0.02 14.    0.5 ]
301



Saving Completed
completed


In [5]:
heads.left_eye_deviation(0)

0 172576
coordinate of the left eye: [ 0.0345545  -0.17854231 -0.02274339] in frame 0
1 172581
coordinate of the left eye: [ 0.03640054 -0.17906708 -0.01864559] in frame 1
12 169336
coordinate of the left eye: [ 0.0423335  -0.15481534  0.03370858] in frame 12
13 170000
coordinate of the left eye: [ 0.03882328 -0.1541353   0.03081354] in frame 13
14 169380
coordinate of the left eye: [ 0.03710537 -0.15637763  0.03361353] in frame 14
[ 0.03784344 -0.16458753  0.01134933]
[[-0.00328894 -0.01395478 -0.03409273]
 [-0.0014429  -0.01447955 -0.02999493]
 [ 0.00449006  0.00977219  0.02235924]
 [ 0.00097984  0.01045223  0.01946421]
 [-0.00073807  0.0082099   0.0222642 ]]
mean coordinate: [ 0.03784344 -0.16458753  0.01134933]. Distance to each points: [0.03698468 0.03333819 0.02481113 0.02211481 0.02374114].


(array([ 0.03784344, -0.16458753,  0.01134933]),
 array([0.03698468, 0.03333819, 0.02481113, 0.02211481, 0.02374114]))

In [9]:
heads.left_eye_deviation(1)

0 153974
coordinate of the left eye: [ 0.01958677 -0.12910025 -0.00640524] in frame 0
1 150143
coordinate of the left eye: [ 0.02184315 -0.12885785 -0.00816567] in frame 1
2 150124
coordinate of the left eye: [ 0.01827939 -0.12761078 -0.01151653] in frame 2
13 147576
coordinate of the left eye: [-0.00435965 -0.13210005 -0.00961363] in frame 13
14 150775
coordinate of the left eye: [-0.00726736 -0.12949743 -0.01545459] in frame 14
[ 0.00961646 -0.12943327 -0.01023113]
[[ 9.97031059e-03  3.33022414e-04  3.82588835e-03]
 [ 1.22266925e-02  5.75420423e-04  2.06546226e-03]
 [ 8.66292738e-03  1.82249184e-03 -1.28539527e-03]
 [-1.39761117e-02 -2.66677491e-03  6.17499115e-04]
 [-1.68838187e-02 -6.41597689e-05 -5.22345446e-03]]
mean coordinate: [ 0.00961646 -0.12943327 -0.01023113]. Distance to each points: [0.01068435 0.01241327 0.00894539 0.01424165 0.01767348].


(array([ 0.00961646, -0.12943327, -0.01023113]),
 array([0.01068435, 0.01241327, 0.00894539, 0.01424165, 0.01767348]))

In [13]:
heads.left_eye_deviation(2)

0 152103
coordinate of the left eye: [ 0.0477391  -0.16602056  0.00701409] in frame 0
1 152745
coordinate of the left eye: [ 0.05224443 -0.16629774  0.0119082 ] in frame 1
12 150113
coordinate of the left eye: [ 0.08484852 -0.13831299  0.12609314] in frame 12
13 149516
coordinate of the left eye: [ 0.0773928  -0.14083417  0.13746829] in frame 13
14 151469
coordinate of the left eye: [ 0.07982782 -0.13955872  0.13644406] in frame 14
[ 0.06841054 -0.15020484  0.08378556]
[[-0.02067143 -0.01581572 -0.07677146]
 [-0.01616611 -0.01609291 -0.07187736]
 [ 0.01643798  0.01189185  0.04230758]
 [ 0.00898227  0.00937066  0.05368274]
 [ 0.01141729  0.01064612  0.0526585 ]]
mean coordinate: [ 0.06841054 -0.15020484  0.08378556]. Distance to each points: [0.08106357 0.07541007 0.04692073 0.05522976 0.05492369].


(array([ 0.06841054, -0.15020484,  0.08378556]),
 array([0.08106357, 0.07541007, 0.04692073, 0.05522976, 0.05492369]))

In [6]:
heads.left_eye_deviation(3)

0 116190


IndexError: index 116190 is out of bounds for axis 0 with size 70610