In [1]:
import HEAD_RECON
import multi_head
import copy
import numpy as np
import matplotlib.pyplot as plt
import cv2
from scipy.ndimage.morphology import binary_fill_holes
import sys
np.set_printoptions(threshold=sys.maxsize)

%load_ext autoreload
%autoreload 2

<IPython.core.display.Javascript object>

In [ ]:
# gen 2d images
for i in range(1,16):
    print(i)
    head = HEAD_RECON.threeD_head.read_from_file(1,i)
    head.reset_filters()
    head.filter_nan()
    head.filter_depth(1.5)
    head.sparsify(1)
    head.parzen_filter(p=6,r=0.006)
    print("dangling removal done")
#     head.remove_background_color()
    print("color filter done.")
#     head.edge_based_filter()
#     head.erode_filter(5)
#     head.filter_depth(1.5)
#     head.remove_dangling()
    head.center()
    head.get_filtered_image()
    head.create_vpython_spheres()
    head.save()

1
0 53999
1 53999
2 53999
3 53999
4 53999
5 53999
6 53999
7 53999
8 53999
9 53999
10 53999
11 53999
12 53999
13 53999
14 53999
15 53999
16 53999
17 53999
18 53999
19 53999
20 53999
21 53999
22 53999
23 53999
24 53999
25 53999
26 53999
27 53999
28 53999
29 53999
30 53999
31 53999
32 53999
33 53999
34 53999
35 53999
36 53999
37 53999
38 53999
39 53999
40 53999
41 53999
42 53999
43 53999
44 53999
45 53999
46 53999
47 53999
48 53999
49 53999
50 53999
51 53999
52 53999
53 53999
54 53999
55 53999
56 53999
57 53999
58 53999
59 53999
60 53999
61 53999
62 53999
63 53999
64 53999
65 53999
66 53999
67 53999
68 53999
69 53999
70 53999
71 53999
72 53999
73 53999
74 53999
75 53999
76 53999
77 53999
78 53999
79 53999
80 53999
81 53999
82 53999
83 53999
84 53999
85 53999
86 53999
87 53999
88 53999
89 53999
90 53999
91 53999
92 53999
93 53999
94 53999
95 53999
96 53999
97 53999
98 53999
99 53999
100 53999
101 53999
102 53999
103 53999
113 53999
114 53999
115 53999
118 53999
119 53999
120 53999
121 5399

11073 53999
11074 53999
11075 53999
11076 53999
11184 53999
11185 53999
11186 53999
11187 53999
11188 53999
11189 53999
11190 53999
11191 53999
11298 53999
11299 53999
11300 53999
11301 53999
11302 53999
11303 53999
11304 53999
11409 53999
11410 53999
11411 53999
11412 53999
11413 53999
11414 53999
11519 53999
11520 53999
11521 53999
11522 53999
11523 53999
11524 53999
11525 53999
11628 53999
11629 53999
11630 53999
11631 53999
11632 53999
11633 53999
11634 53999
11735 53999
11736 53999
11737 53999
11738 53999
11739 53999
11740 53999
11741 53999
11840 53999
11841 53999
11842 53999
11843 53999
11844 53999
11845 53999
11846 53999
11847 53999
11945 53999
11946 53999
11947 53999
11948 53999
11949 53999
11950 53999
12047 53999
12048 53999
12049 53999
12050 53999
12051 53999
12147 53999
12148 53999
12149 53999
12150 53999
12151 53999
12152 53999
12153 53999
12248 53999
12249 53999
12250 53999
12251 53999
12252 53999
12253 53999
12254 53999
12255 53999
12347 53999
12348 53999
12349 53999
1235

17574 53999
17575 53999
17576 53999
17577 53999
17578 53999
17579 53999
17580 53999
17581 53999
17582 53999
17583 53999
17584 53999
17797 53999
17798 53999
17799 53999
17800 53999
17801 53999
17802 53999
17803 53999
17804 53999
17805 53999
17806 53999
18024 53999
18025 53999
18026 53999
18027 53999
18028 53999
18029 53999
18030 53999
18031 53999
18032 53999
18033 53999
18034 53999
18255 53999
18256 53999
18257 53999
18258 53999
18259 53999
18260 53999
18261 53999
18262 53999
18263 53999
18264 53999
18489 53999
18490 53999
18491 53999
18492 53999
18493 53999
18494 53999
18495 53999
18496 53999
18497 53999
18725 53999
18726 53999
18727 53999
18728 53999
18729 53999
18730 53999
18731 53999
18732 53999
18733 53999
18963 53999
18964 53999
18965 53999
18966 53999
18967 53999
18968 53999
18969 53999
18970 53999
19202 53999
19203 53999
19204 53999
19205 53999
19206 53999
19207 53999
19208 53999
19443 53999
19444 53999
19445 53999
19446 53999
19447 53999
19448 53999
19449 53999
19684 53999
1968

44396 53999
44397 53999
44398 53999
44399 53999
44400 53999
44712 53999
44713 53999
44714 53999
44715 53999
44716 53999
44717 53999
45028 53999
45029 53999
45030 53999
45031 53999
45032 53999
45033 53999
45346 53999
45347 53999
45348 53999
45349 53999
45350 53999
45663 53999
45664 53999
45665 53999
45666 53999
45667 53999
45668 53999
45669 53999
45670 53999
45984 53999
45985 53999
45986 53999
45987 53999
45988 53999
45989 53999
45990 53999
46305 53999
46306 53999
46307 53999
46308 53999
46309 53999
46310 53999
46626 53999
46627 53999
46628 53999
46629 53999
46630 53999
46631 53999
46632 53999
46633 53999
46634 53999
46951 53999
46952 53999
46953 53999
46954 53999
46955 53999
46956 53999
46957 53999
47274 53999
47275 53999
47276 53999
47277 53999
47278 53999
47279 53999
47595 53999
47596 53999
47597 53999
47598 53999
47599 53999
47600 53999
47916 53999
47917 53999
47918 53999
47919 53999
47920 53999
47921 53999
48237 53999
48238 53999
48239 53999
48240 53999
48241 53999
48558 53999
4855

53544 53999
53545 53999
53546 53999
53547 53999
53548 53999
53549 53999
53550 53999
53551 53999
53552 53999
53553 53999
53554 53999
53555 53999
53556 53999
53557 53999
53558 53999
53559 53999
53560 53999
53561 53999
53562 53999
53563 53999
53564 53999
53565 53999
53566 53999
53567 53999
53568 53999
53569 53999
53570 53999
53571 53999
53572 53999
53573 53999
53574 53999
53575 53999
53576 53999
53577 53999
53578 53999
53579 53999
53580 53999
53581 53999
53582 53999
53583 53999
53584 53999
53585 53999
53586 53999
53587 53999
53588 53999
53589 53999
53590 53999
53591 53999
53592 53999
53593 53999
53594 53999
53595 53999
53596 53999
53597 53999
53598 53999
53599 53999
53600 53999
53601 53999
53602 53999
53603 53999
53604 53999
53605 53999
53606 53999
53607 53999
53608 53999
53609 53999
53610 53999
53611 53999
53612 53999
53613 53999
53614 53999
53615 53999
53616 53999
53617 53999
53618 53999
53619 53999
53620 53999
53621 53999
53622 53999
53623 53999
53624 53999
53625 53999
53626 53999
5362

1398 53888
1399 53888
1400 53888
1401 53888
1402 53888
1494 53888
1495 53888
1496 53888
1497 53888
1498 53888
1499 53888
1500 53888
1594 53888
1595 53888
1596 53888
1597 53888
1598 53888
1599 53888
1694 53888
1695 53888
1696 53888
1697 53888
1698 53888
1699 53888
1796 53888
1797 53888
1798 53888
1799 53888
1800 53888
1801 53888
1898 53888
1899 53888
1900 53888
1901 53888
1902 53888
1903 53888
1904 53888
2002 53888
2003 53888
2004 53888
2005 53888
2006 53888
2007 53888
2008 53888
2107 53888
2108 53888
2109 53888
2110 53888
2111 53888
2112 53888
2213 53888
2214 53888
2215 53888
2216 53888
2217 53888
2218 53888
2219 53888
2220 53888
2221 53888
2322 53888
2323 53888
2324 53888
2325 53888
2326 53888
2327 53888
2328 53888
2432 53888
2433 53888
2434 53888
2435 53888
2436 53888
2437 53888
2438 53888
2542 53888
2543 53888
2544 53888
2545 53888
2546 53888
2651 53888
2652 53888
2653 53888
2654 53888
2655 53888
2656 53888
2657 53888
2658 53888
2763 53888
2764 53888
2765 53888
2766 53888
2767 53888

13544 53888
13545 53888
13546 53888
13547 53888
13617 53888
13618 53888
13619 53888
13620 53888
13621 53888
13622 53888
13623 53888
13624 53888
13625 53888
13695 53888
13696 53888
13697 53888
13698 53888
13699 53888
13700 53888
13701 53888
13771 53888
13772 53888
13773 53888
13774 53888
13775 53888
13776 53888
13848 53888
13849 53888
13850 53888
13851 53888
13852 53888
13853 53888
13854 53888
13925 53888
13926 53888
13927 53888
13928 53888
13929 53888
13930 53888
13931 53888
13932 53888
14002 53888
14003 53888
14004 53888
14005 53888
14006 53888
14007 53888
14008 53888
14077 53888
14078 53888
14079 53888
14080 53888
14081 53888
14082 53888
14083 53888
14084 53888
14152 53888
14153 53888
14154 53888
14155 53888
14223 53888
14224 53888
14225 53888
14226 53888
14227 53888
14228 53888
14229 53888
14297 53888
14298 53888
14299 53888
14300 53888
14301 53888
14302 53888
14303 53888
14304 53888
14305 53888
14373 53888
14374 53888
14375 53888
14376 53888
14377 53888
14378 53888
14379 53888
1438

26431 53888
26432 53888
26433 53888
26434 53888
26435 53888
26436 53888
26437 53888
26438 53888
26714 53888
26715 53888
26716 53888
26717 53888
26718 53888
26719 53888
26720 53888
26995 53888
26996 53888
26997 53888
26998 53888
26999 53888
27000 53888
27001 53888
27002 53888
27003 53888
27276 53888
27277 53888
27278 53888
27279 53888
27280 53888
27281 53888
27282 53888
27283 53888
27284 53888
27285 53888
27286 53888
27558 53888
27559 53888
27560 53888
27561 53888
27562 53888
27563 53888
27564 53888
27836 53888
27837 53888
27838 53888
27839 53888
27840 53888
27841 53888
28111 53888
28112 53888
28113 53888
28114 53888
28115 53888
28385 53888
28386 53888
28387 53888
28388 53888
28389 53888
28390 53888
28660 53888
28661 53888
28662 53888
28663 53888
28664 53888
28665 53888
28936 53888
28937 53888
28938 53888
28939 53888
28940 53888
28941 53888
28942 53888
29214 53888
29215 53888
29216 53888
29217 53888
29218 53888
29490 53888
29491 53888
29492 53888
29493 53888
29494 53888
29495 53888
2976

53183 53888
53184 53888
53185 53888
53186 53888
53187 53888
53188 53888
53189 53888
53190 53888
53191 53888
53192 53888
53193 53888
53194 53888
53195 53888
53196 53888
53197 53888
53198 53888
53199 53888
53200 53888
53201 53888
53202 53888
53203 53888
53204 53888
53205 53888
53206 53888
53207 53888
53208 53888
53209 53888
53210 53888
53211 53888
53212 53888
53213 53888
53214 53888
53215 53888
53216 53888
53217 53888
53218 53888
53219 53888
53220 53888
53221 53888
53222 53888
53223 53888
53224 53888
53225 53888
53226 53888
53227 53888
53228 53888
53229 53888
53230 53888
53231 53888
53232 53888
53233 53888
53234 53888
53235 53888
53236 53888
53237 53888
53238 53888
53239 53888
53240 53888
53241 53888
53242 53888
53243 53888
53244 53888
53245 53888
53246 53888
53247 53888
53248 53888
53249 53888
53250 53888
53251 53888
53252 53888
53253 53888
53254 53888
53255 53888
53256 53888
53257 53888
53258 53888
53259 53888
53260 53888
53261 53888
53262 53888
53263 53888
53264 53888
53265 53888
5326

34 53837
35 53837
36 53837
37 53837
38 53837
39 53837
40 53837
41 53837
42 53837
43 53837
44 53837
45 53837
46 53837
47 53837
48 53837
49 53837
50 53837
51 53837
52 53837
53 53837
54 53837
55 53837
56 53837
57 53837
58 53837
59 53837
60 53837
61 53837
62 53837
63 53837
64 53837
65 53837
66 53837
67 53837
68 53837
69 53837
70 53837
71 53837
72 53837
73 53837
74 53837
75 53837
76 53837
77 53837
78 53837
79 53837
80 53837
81 53837
82 53837
83 53837
84 53837
85 53837
86 53837
87 53837
88 53837
89 53837
90 53837
91 53837
92 53837
93 53837
94 53837
95 53837
96 53837
97 53837
98 53837
99 53837
100 53837
101 53837
111 53837
112 53837
113 53837
116 53837
117 53837
118 53837
119 53837
120 53837
121 53837
122 53837
123 53837
124 53837
125 53837
126 53837
127 53837
128 53837
129 53837
130 53837
131 53837
132 53837
133 53837
134 53837
135 53837
136 53837
137 53837
138 53837
139 53837
140 53837
141 53837
142 53837
143 53837
144 53837
145 53837
146 53837
147 53837
148 53837
149 53837
150 53837
180 53

11363 53837
11364 53837
11365 53837
11366 53837
11367 53837
11468 53837
11469 53837
11470 53837
11471 53837
11472 53837
11473 53837
11474 53837
11475 53837
11575 53837
11576 53837
11577 53837
11578 53837
11579 53837
11580 53837
11679 53837
11680 53837
11681 53837
11682 53837
11683 53837
11781 53837
11782 53837
11783 53837
11784 53837
11785 53837
11786 53837
11883 53837
11884 53837
11885 53837
11886 53837
11887 53837
11888 53837
11889 53837
11985 53837
11986 53837
11987 53837
11988 53837
11989 53837
11990 53837
12085 53837
12086 53837
12087 53837
12088 53837
12089 53837
12090 53837
12091 53837
12186 53837
12187 53837
12188 53837
12189 53837
12190 53837
12191 53837
12192 53837
12193 53837
12285 53837
12286 53837
12287 53837
12288 53837
12289 53837
12290 53837
12291 53837
12292 53837
12293 53837
12294 53837
12295 53837
12296 53837
12297 53837
12298 53837
12299 53837
12385 53837
12386 53837
12387 53837
12388 53837
12389 53837
12390 53837
12391 53837
12392 53837
12393 53837
12394 53837
1239

17911 53837
17912 53837
17913 53837
17914 53837
17915 53837
17916 53837
18136 53837
18137 53837
18138 53837
18139 53837
18140 53837
18141 53837
18142 53837
18143 53837
18144 53837
18145 53837
18368 53837
18369 53837
18370 53837
18371 53837
18372 53837
18373 53837
18374 53837
18375 53837
18376 53837
18377 53837
18603 53837
18604 53837
18605 53837
18606 53837
18607 53837
18608 53837
18609 53837
18610 53837
18611 53837
18612 53837
18613 53837
18841 53837
18842 53837
18843 53837
18844 53837
18845 53837
18846 53837
18847 53837
18848 53837
18849 53837
18850 53837
19080 53837
19081 53837
19082 53837
19083 53837
19317 53837
19318 53837
19319 53837
19320 53837
19321 53837
19322 53837
19323 53837
19324 53837
19558 53837
19559 53837
19560 53837
19561 53837
19562 53837
19563 53837
19564 53837
19565 53837
19566 53837
19567 53837
19802 53837
19803 53837
19804 53837
19805 53837
19806 53837
19807 53837
19808 53837
19809 53837
19810 53837
19811 53837
19812 53837
20050 53837
20051 53837
20052 53837
2005

49697 53837
49698 53837
49699 53837
49700 53837
49701 53837
50020 53837
50021 53837
50022 53837
50023 53837
50024 53837
50343 53837
50344 53837
50345 53837
50346 53837
50347 53837
50667 53837
50668 53837
50669 53837
50670 53837
50671 53837
50672 53837
50673 53837
50674 53837
50995 53837
50996 53837
50997 53837
50998 53837
50999 53837
51000 53837
51322 53837
51323 53837
51324 53837
51325 53837
51326 53837
51327 53837
51328 53837
51651 53837
51652 53837
51653 53837
51654 53837
51655 53837
51656 53837
51979 53837
51980 53837
51981 53837
51982 53837
51983 53837
51984 53837
51985 53837
51986 53837
52310 53837
52311 53837
52312 53837
52313 53837
52638 53837
52639 53837
52640 53837
52641 53837
52642 53837
52643 53837
52644 53837
52645 53837
52646 53837
52647 53837
52648 53837
52649 53837
52650 53837
52651 53837
52652 53837
52653 53837
52654 53837
52655 53837
52656 53837
52657 53837
52658 53837
52659 53837
52660 53837
52661 53837
52662 53837
52663 53837
52664 53837
52665 53837
52666 53837
5266

53548 53837
53549 53837
53550 53837
53551 53837
53552 53837
53553 53837
53554 53837
53555 53837
53556 53837
53557 53837
53558 53837
53559 53837
53560 53837
53561 53837
53562 53837
53563 53837
53564 53837
53565 53837
53566 53837
53567 53837
53568 53837
53569 53837
53570 53837
53571 53837
53572 53837
53573 53837
53574 53837
53575 53837
53576 53837
53577 53837
53578 53837
53579 53837
53580 53837
53581 53837
53582 53837
53583 53837
53584 53837
53585 53837
53586 53837
53587 53837
53588 53837
53589 53837
53590 53837
53591 53837
53592 53837
53593 53837
53594 53837
53595 53837
53596 53837
53597 53837
53598 53837
53599 53837
53600 53837
53601 53837
53602 53837
53603 53837
53604 53837
53605 53837
53606 53837
53607 53837
53608 53837
53609 53837
53610 53837
53611 53837
53612 53837
53613 53837
53614 53837
53615 53837
53616 53837
53617 53837
53618 53837
53619 53837
53620 53837
53621 53837
53622 53837
53623 53837
53624 53837
53625 53837
53626 53837
53627 53837
53628 53837
53629 53837
53630 53837
5363

5654 53812
5655 53812
5656 53812
5769 53812
5770 53812
5771 53812
5772 53812
5773 53812
5774 53812
5887 53812
5888 53812
5889 53812
5890 53812
5891 53812
5892 53812
6005 53812
6006 53812
6007 53812
6008 53812
6009 53812
6010 53812
6123 53812
6124 53812
6125 53812
6126 53812
6127 53812
6128 53812
6241 53812
6242 53812
6243 53812
6244 53812
6245 53812
6246 53812
6359 53812
6360 53812
6361 53812
6362 53812
6363 53812
6364 53812
6477 53812
6478 53812
6479 53812
6480 53812
6481 53812
6482 53812
6483 53812
6596 53812
6597 53812
6598 53812
6599 53812
6600 53812
6601 53812
6602 53812
6715 53812
6716 53812
6717 53812
6718 53812
6719 53812
6832 53812
6833 53812
6834 53812
6835 53812
6836 53812
6837 53812
6838 53812
6839 53812
6840 53812
6953 53812
6954 53812
6955 53812
6956 53812
6957 53812
6958 53812
6959 53812
6960 53812
6961 53812
7075 53812
7076 53812
7077 53812
7078 53812
7079 53812
7080 53812
7081 53812
7082 53812
7083 53812
7084 53812
7198 53812
7199 53812
7200 53812
7201 53812
7202 53812

15127 53812
15128 53812
15129 53812
15130 53812
15131 53812
15132 53812
15133 53812
15134 53812
15135 53812
15136 53812
15137 53812
15138 53812
15139 53812
15140 53812
15141 53812
15142 53812
15143 53812
15144 53812
15145 53812
15146 53812
15147 53812
15148 53812
15271 53812
15272 53812
15273 53812
15274 53812
15275 53812
15276 53812
15277 53812
15278 53812
15279 53812
15280 53812
15281 53812
15282 53812
15283 53812
15284 53812
15285 53812
15286 53812
15287 53812
15288 53812
15289 53812
15290 53812
15291 53812
15292 53812
15293 53812
15294 53812
15295 53812
15296 53812
15297 53812
15298 53812
15436 53812
15437 53812
15438 53812
15439 53812
15440 53812
15441 53812
15442 53812
15443 53812
15444 53812
15445 53812
15446 53812
15447 53812
15448 53812
15449 53812
15450 53812
15451 53812
15452 53812
15453 53812
15454 53812
15455 53812
15456 53812
15457 53812
15458 53812
15459 53812
15460 53812
15461 53812
15462 53812
15463 53812
15464 53812
15465 53812
15466 53812
15618 53812
15619 53812
1562

32779 53812
32780 53812
32781 53812
32782 53812
32783 53812
32784 53812
32785 53812
33065 53812
33066 53812
33067 53812
33068 53812
33069 53812
33070 53812
33071 53812
33353 53812
33354 53812
33355 53812
33356 53812
33357 53812
33639 53812
33640 53812
33641 53812
33642 53812
33643 53812
33644 53812
33927 53812
33928 53812
33929 53812
33930 53812
33931 53812
33932 53812
34216 53812
34217 53812
34218 53812
34219 53812
34220 53812
34221 53812
34222 53812
34506 53812
34507 53812
34508 53812
34509 53812
34510 53812
34511 53812
34512 53812
34798 53812
34799 53812
34800 53812
34801 53812
34802 53812
34803 53812
34804 53812
35090 53812
35091 53812
35092 53812
35093 53812
35094 53812
35381 53812
35382 53812
35383 53812
35384 53812
35385 53812
35673 53812
35674 53812
35675 53812
35676 53812
35964 53812
35965 53812
35966 53812
35967 53812
35968 53812
35969 53812
35970 53812
36259 53812
36260 53812
36261 53812
36262 53812
36263 53812
36264 53812
36553 53812
36554 53812
36555 53812
36556 53812
3655

53097 53812
53098 53812
53099 53812
53100 53812
53101 53812
53102 53812
53103 53812
53104 53812
53105 53812
53106 53812
53107 53812
53108 53812
53109 53812
53110 53812
53111 53812
53112 53812
53113 53812
53114 53812
53115 53812
53116 53812
53117 53812
53118 53812
53119 53812
53120 53812
53121 53812
53122 53812
53123 53812
53124 53812
53125 53812
53126 53812
53127 53812
53128 53812
53129 53812
53130 53812
53131 53812
53132 53812
53133 53812
53134 53812
53135 53812
53136 53812
53137 53812
53138 53812
53139 53812
53140 53812
53141 53812
53142 53812
53143 53812
53144 53812
53145 53812
53146 53812
53147 53812
53148 53812
53149 53812
53150 53812
53151 53812
53152 53812
53153 53812
53154 53812
53155 53812
53156 53812
53157 53812
53158 53812
53159 53812
53160 53812
53161 53812
53162 53812
53163 53812
53164 53812
53165 53812
53166 53812
53167 53812
53168 53812
53169 53812
53170 53812
53171 53812
53172 53812
53173 53812
53174 53812
53175 53812
53176 53812
53177 53812
53178 53812
53179 53812
5318

12 53792
13 53792
14 53792
15 53792
16 53792
17 53792
18 53792
19 53792
20 53792
21 53792
22 53792
23 53792
24 53792
25 53792
26 53792
27 53792
28 53792
29 53792
30 53792
31 53792
32 53792
33 53792
34 53792
35 53792
36 53792
37 53792
38 53792
39 53792
40 53792
41 53792
42 53792
43 53792
44 53792
45 53792
46 53792
47 53792
48 53792
49 53792
50 53792
51 53792
52 53792
53 53792
54 53792
55 53792
56 53792
57 53792
58 53792
59 53792
60 53792
61 53792
62 53792
63 53792
64 53792
65 53792
66 53792
67 53792
68 53792
69 53792
70 53792
71 53792
72 53792
73 53792
74 53792
75 53792
76 53792
77 53792
78 53792
79 53792
80 53792
81 53792
82 53792
83 53792
84 53792
85 53792
86 53792
87 53792
88 53792
89 53792
90 53792
91 53792
92 53792
93 53792
94 53792
95 53792
96 53792
97 53792
98 53792
99 53792
100 53792
101 53792
111 53792
112 53792
113 53792
116 53792
117 53792
118 53792
119 53792
120 53792
121 53792
122 53792
123 53792
124 53792
125 53792
126 53792
127 53792
128 53792
129 53792
130 53792
131 5379

10323 53792
10433 53792
10434 53792
10435 53792
10436 53792
10437 53792
10438 53792
10439 53792
10440 53792
10441 53792
10442 53792
10443 53792
10552 53792
10553 53792
10554 53792
10555 53792
10556 53792
10557 53792
10558 53792
10559 53792
10560 53792
10561 53792
10562 53792
10670 53792
10671 53792
10672 53792
10673 53792
10674 53792
10675 53792
10676 53792
10677 53792
10678 53792
10786 53792
10787 53792
10788 53792
10789 53792
10790 53792
10791 53792
10898 53792
10899 53792
10900 53792
10901 53792
10902 53792
10903 53792
10904 53792
10905 53792
11012 53792
11013 53792
11014 53792
11015 53792
11016 53792
11017 53792
11018 53792
11019 53792
11125 53792
11126 53792
11127 53792
11128 53792
11129 53792
11130 53792
11131 53792
11132 53792
11238 53792
11239 53792
11240 53792
11241 53792
11242 53792
11243 53792
11244 53792
11245 53792
11246 53792
11247 53792
11348 53792
11349 53792
11350 53792
11351 53792
11352 53792
11353 53792
11354 53792
11355 53792
11356 53792
11457 53792
11458 53792
1145

18341 53792
18342 53792
18343 53792
18344 53792
18345 53792
18346 53792
18347 53792
18348 53792
18349 53792
18350 53792
18576 53792
18577 53792
18578 53792
18579 53792
18580 53792
18581 53792
18582 53792
18583 53792
18584 53792
18585 53792
18586 53792
18814 53792
18815 53792
18816 53792
18817 53792
18818 53792
18819 53792
18820 53792
18821 53792
18822 53792
18823 53792
19052 53792
19053 53792
19054 53792
19055 53792
19056 53792
19288 53792
19289 53792
19290 53792
19291 53792
19292 53792
19293 53792
19294 53792
19295 53792
19296 53792
19297 53792
19529 53792
19530 53792
19531 53792
19532 53792
19533 53792
19534 53792
19535 53792
19536 53792
19537 53792
19538 53792
19539 53792
19540 53792
19773 53792
19774 53792
19775 53792
19776 53792
19777 53792
19778 53792
19779 53792
19780 53792
19781 53792
19782 53792
19783 53792
20020 53792
20021 53792
20022 53792
20023 53792
20024 53792
20025 53792
20026 53792
20027 53792
20028 53792
20029 53792
20268 53792
20269 53792
20270 53792
20271 53792
2051

48684 53792
48685 53792
48686 53792
49004 53792
49005 53792
49006 53792
49007 53792
49008 53792
49009 53792
49010 53792
49011 53792
49012 53792
49330 53792
49331 53792
49332 53792
49333 53792
49652 53792
49653 53792
49654 53792
49655 53792
49656 53792
49975 53792
49976 53792
49977 53792
49978 53792
49979 53792
50298 53792
50299 53792
50300 53792
50301 53792
50302 53792
50622 53792
50623 53792
50624 53792
50625 53792
50626 53792
50627 53792
50628 53792
50629 53792
50950 53792
50951 53792
50952 53792
50953 53792
50954 53792
50955 53792
51277 53792
51278 53792
51279 53792
51280 53792
51281 53792
51282 53792
51283 53792
51606 53792
51607 53792
51608 53792
51609 53792
51610 53792
51611 53792
51934 53792
51935 53792
51936 53792
51937 53792
51938 53792
51939 53792
51940 53792
51941 53792
52265 53792
52266 53792
52267 53792
52268 53792
52593 53792
52594 53792
52595 53792
52596 53792
52597 53792
52598 53792
52599 53792
52600 53792
52601 53792
52602 53792
52603 53792
52604 53792
52605 53792
5260

53480 53792
53481 53792
53482 53792
53483 53792
53484 53792
53485 53792
53486 53792
53487 53792
53488 53792
53489 53792
53490 53792
53491 53792
53492 53792
53493 53792
53494 53792
53495 53792
53496 53792
53497 53792
53498 53792
53499 53792
53500 53792
53501 53792
53502 53792
53503 53792
53504 53792
53505 53792
53506 53792
53507 53792
53508 53792
53509 53792
53510 53792
53511 53792
53512 53792
53513 53792
53514 53792
53515 53792
53516 53792
53517 53792
53518 53792
53519 53792
53520 53792
53521 53792
53522 53792
53523 53792
53524 53792
53525 53792
53526 53792
53527 53792
53528 53792
53529 53792
53530 53792
53531 53792
53532 53792
53533 53792
53534 53792
53535 53792
53536 53792
53537 53792
53538 53792
53539 53792
53540 53792
53541 53792
53542 53792
53543 53792
53544 53792
53545 53792
53546 53792
53547 53792
53548 53792
53549 53792
53550 53792
53551 53792
53552 53792
53553 53792
53554 53792
53555 53792
53556 53792
53557 53792
53558 53792
53559 53792
53560 53792
53561 53792
53562 53792
5356

5438 53131
5439 53131
5440 53131
5441 53131
5442 53131
5443 53131
5444 53131
5445 53131
5446 53131
5558 53131
5559 53131
5560 53131
5561 53131
5562 53131
5563 53131
5675 53131
5676 53131
5677 53131
5678 53131
5679 53131
5680 53131
5792 53131
5793 53131
5794 53131
5795 53131
5796 53131
5797 53131
5909 53131
5910 53131
5911 53131
5912 53131
5913 53131
5914 53131
6026 53131
6027 53131
6028 53131
6029 53131
6030 53131
6031 53131
6143 53131
6144 53131
6145 53131
6146 53131
6147 53131
6148 53131
6260 53131
6261 53131
6262 53131
6263 53131
6264 53131
6265 53131
6377 53131
6378 53131
6379 53131
6380 53131
6381 53131
6382 53131
6494 53131
6495 53131
6496 53131
6497 53131
6498 53131
6499 53131
6611 53131
6612 53131
6613 53131
6614 53131
6615 53131
6729 53131
6730 53131
6731 53131
6732 53131
6733 53131
6847 53131
6848 53131
6849 53131
6850 53131
6851 53131
6852 53131
6853 53131
6967 53131
6968 53131
6969 53131
6970 53131
6971 53131
6972 53131
6973 53131
6974 53131
6975 53131
6976 53131
7091 53131

16123 53131
16124 53131
16125 53131
16126 53131
16127 53131
16128 53131
16129 53131
16130 53131
16131 53131
16132 53131
16133 53131
16295 53131
16296 53131
16297 53131
16298 53131
16299 53131
16300 53131
16301 53131
16302 53131
16303 53131
16304 53131
16305 53131
16306 53131
16307 53131
16308 53131
16309 53131
16310 53131
16311 53131
16312 53131
16313 53131
16314 53131
16480 53131
16481 53131
16482 53131
16483 53131
16484 53131
16485 53131
16486 53131
16487 53131
16488 53131
16489 53131
16490 53131
16491 53131
16492 53131
16493 53131
16494 53131
16495 53131
16496 53131
16497 53131
16498 53131
16672 53131
16673 53131
16674 53131
16675 53131
16676 53131
16677 53131
16678 53131
16679 53131
16680 53131
16681 53131
16682 53131
16683 53131
16684 53131
16867 53131
16868 53131
16869 53131
16870 53131
16871 53131
16872 53131
16873 53131
16874 53131
16875 53131
16876 53131
17062 53131
17063 53131
17064 53131
17065 53131
17066 53131
17067 53131
17068 53131
17069 53131
17070 53131
17071 53131
1707

37522 53131
37523 53131
37524 53131
37525 53131
37526 53131
37527 53131
37528 53131
37811 53131
37812 53131
37813 53131
37814 53131
37815 53131
37816 53131
37817 53131
37960 53131
37961 53131
37962 53131
37963 53131
37964 53131
38099 53131
38100 53131
38101 53131
38102 53131
38103 53131
38245 53131
38246 53131
38247 53131
38248 53131
38249 53131
38250 53131
38251 53131
38386 53131
38387 53131
38388 53131
38389 53131
38390 53131
38531 53131
38532 53131
38533 53131
38534 53131
38669 53131
38670 53131
38671 53131
38672 53131
38673 53131
38674 53131
38675 53131
38676 53131
38677 53131
38678 53131
38819 53131
38820 53131
38821 53131
38822 53131
38957 53131
38958 53131
38959 53131
38960 53131
38961 53131
38962 53131
39103 53131
39104 53131
39105 53131
39106 53131
39107 53131
39243 53131
39244 53131
39245 53131
39246 53131
39247 53131
39248 53131
39249 53131
39390 53131
39391 53131
39392 53131
39393 53131
39394 53131
39395 53131
39396 53131
39533 53131
39534 53131
39535 53131
39536 53131
3953

52540 53131
52541 53131
52542 53131
52543 53131
52544 53131
52545 53131
52546 53131
52547 53131
52548 53131
52549 53131
52550 53131
52551 53131
52552 53131
52553 53131
52554 53131
52555 53131
52556 53131
52557 53131
52558 53131
52559 53131
52560 53131
52561 53131
52562 53131
52563 53131
52564 53131
52565 53131
52566 53131
52567 53131
52568 53131
52569 53131
52570 53131
52571 53131
52572 53131
52573 53131
52574 53131
52575 53131
52576 53131
52577 53131
52578 53131
52579 53131
52580 53131
52581 53131
52582 53131
52583 53131
52584 53131
52585 53131
52586 53131
52587 53131
52588 53131
52589 53131
52590 53131
52591 53131
52592 53131
52593 53131
52594 53131
52595 53131
52596 53131
52597 53131
52598 53131
52599 53131
52600 53131
52601 53131
52602 53131
52603 53131
52604 53131
52605 53131
52606 53131
52607 53131
52608 53131
52609 53131
52610 53131
52611 53131
52612 53131
52613 53131
52614 53131
52615 53131
52616 53131
52617 53131
52618 53131
52619 53131
52620 53131
52621 53131
52622 53131
5262

520 53083
521 53083
522 53083
523 53083
524 53083
525 53083
526 53083
593 53083
594 53083
595 53083
596 53083
597 53083
598 53083
599 53083
600 53083
601 53083
671 53083
672 53083
673 53083
674 53083
675 53083
676 53083
677 53083
678 53083
750 53083
751 53083
752 53083
753 53083
754 53083
755 53083
756 53083
829 53083
830 53083
831 53083
832 53083
833 53083
834 53083
835 53083
836 53083
837 53083
911 53083
912 53083
913 53083
914 53083
915 53083
916 53083
917 53083
994 53083
995 53083
996 53083
997 53083
998 53083
999 53083
1077 53083
1078 53083
1079 53083
1080 53083
1081 53083
1082 53083
1083 53083
1084 53083
1085 53083
1165 53083
1166 53083
1167 53083
1168 53083
1169 53083
1170 53083
1171 53083
1252 53083
1253 53083
1254 53083
1255 53083
1256 53083
1257 53083
1258 53083
1341 53083
1342 53083
1343 53083
1344 53083
1345 53083
1346 53083
1347 53083
1348 53083
1433 53083
1434 53083
1435 53083
1436 53083
1437 53083
1438 53083
1439 53083
1440 53083
1441 53083
1442 53083
1443 53083
1444 530

13001 53083
13002 53083
13003 53083
13004 53083
13005 53083
13090 53083
13091 53083
13092 53083
13093 53083
13094 53083
13178 53083
13179 53083
13180 53083
13181 53083
13182 53083
13183 53083
13184 53083
13185 53083
13269 53083
13270 53083
13271 53083
13272 53083
13273 53083
13274 53083
13275 53083
13358 53083
13359 53083
13360 53083
13361 53083
13362 53083
13363 53083
13364 53083
13365 53083
13446 53083
13447 53083
13448 53083
13449 53083
13450 53083
13451 53083
13532 53083
13533 53083
13534 53083
13535 53083
13536 53083
13537 53083
13538 53083
13617 53083
13618 53083
13619 53083
13620 53083
13621 53083
13622 53083
13623 53083
13701 53083
13702 53083
13703 53083
13704 53083
13705 53083
13706 53083
13783 53083
13784 53083
13785 53083
13786 53083
13787 53083
13788 53083
13864 53083
13865 53083
13866 53083
13867 53083
13868 53083
13869 53083
13944 53083
13945 53083
13946 53083
13947 53083
13948 53083
13949 53083
14023 53083
14024 53083
14025 53083
14026 53083
14027 53083
14028 53083
1410

20278 53083
20279 53083
20280 53083
20526 53083
20527 53083
20528 53083
20529 53083
20530 53083
20531 53083
20532 53083
20533 53083
20534 53083
20535 53083
20783 53083
20784 53083
20785 53083
20786 53083
20787 53083
20788 53083
20789 53083
20790 53083
20791 53083
21042 53083
21043 53083
21044 53083
21045 53083
21046 53083
21047 53083
21048 53083
21301 53083
21302 53083
21303 53083
21304 53083
21305 53083
21306 53083
21559 53083
21560 53083
21561 53083
21562 53083
21563 53083
21564 53083
21565 53083
21820 53083
21821 53083
21822 53083
21823 53083
21824 53083
21825 53083
21826 53083
22083 53083
22084 53083
22085 53083
22086 53083
22087 53083
22088 53083
22345 53083
22346 53083
22347 53083
22348 53083
22349 53083
22350 53083
22351 53083
22352 53083
22611 53083
22612 53083
22613 53083
22614 53083
22615 53083
22616 53083
22877 53083
22878 53083
22879 53083
22880 53083
22881 53083
22882 53083
22883 53083
23144 53083
23145 53083
23146 53083
23147 53083
23148 53083
23149 53083
23411 53083
2341

50362 53083
50363 53083
50364 53083
50365 53083
50366 53083
50367 53083
50675 53083
50676 53083
50677 53083
50678 53083
50679 53083
50989 53083
50990 53083
50991 53083
50992 53083
50993 53083
50994 53083
50995 53083
50996 53083
50997 53083
51307 53083
51308 53083
51309 53083
51310 53083
51311 53083
51312 53083
51313 53083
51314 53083
51625 53083
51626 53083
51627 53083
51628 53083
51629 53083
51630 53083
51631 53083
51632 53083
51943 53083
51944 53083
51945 53083
51946 53083
51947 53083
51954 53083
51955 53083
51956 53083
51957 53083
51958 53083
51959 53083
51960 53083
51961 53083
51962 53083
51963 53083
51964 53083
51965 53083
51966 53083
51967 53083
51968 53083
51969 53083
51970 53083
51971 53083
51972 53083
51973 53083
51974 53083
51975 53083
51976 53083
51977 53083
51978 53083
51979 53083
51980 53083
51981 53083
51982 53083
51983 53083
51984 53083
51985 53083
51986 53083
51987 53083
51988 53083
51989 53083
51990 53083
51991 53083
51992 53083
51993 53083
51994 53083
51995 53083
5199

52854 53083
52855 53083
52856 53083
52857 53083
52858 53083
52859 53083
52860 53083
52861 53083
52862 53083
52863 53083
52864 53083
52865 53083
52866 53083
52867 53083
52868 53083
52869 53083
52870 53083
52871 53083
52872 53083
52873 53083
52874 53083
52875 53083
52876 53083
52877 53083
52878 53083
52879 53083
52880 53083
52881 53083
52882 53083
52883 53083
52884 53083
52885 53083
52886 53083
52887 53083
52888 53083
52889 53083
52890 53083
52891 53083
52892 53083
52893 53083
52894 53083
52895 53083
52896 53083
52897 53083
52898 53083
52899 53083
52900 53083
52901 53083
52902 53083
52903 53083
52904 53083
52905 53083
52906 53083
52907 53083
52908 53083
52909 53083
52910 53083
52911 53083
52912 53083
52913 53083
52914 53083
52915 53083
52916 53083
52917 53083
52918 53083
52919 53083
52920 53083
52921 53083
52922 53083
52923 53083
52924 53083
52925 53083
52926 53083
52927 53083
52928 53083
52929 53083
52930 53083
52931 53083
52932 53083
52933 53083
52934 53083
52935 53083
52936 53083
5293

In [2]:
# gen pickled heads
for p in range(2,3):
    for i in range(1,16):
        print(i)
        head = HEAD_RECON.threeD_head.read_from_file(p,i)
        head.full_filter()
        head.get_filtered_image()

1
(307200,)
depth filter done.
dangling removal done
color filter done.
2
(307200,)
depth filter done.
dangling removal done
color filter done.
3
(307200,)
depth filter done.
dangling removal done
color filter done.
4
(307200,)
depth filter done.
dangling removal done
color filter done.
5
(307200,)
depth filter done.
dangling removal done
color filter done.
6
(307200,)
depth filter done.
dangling removal done
color filter done.
7
(307200,)
depth filter done.
dangling removal done
color filter done.
8
(307200,)
depth filter done.
dangling removal done
color filter done.
9
(307200,)
depth filter done.
dangling removal done
color filter done.
10
(307200,)
depth filter done.
dangling removal done
color filter done.
11
(307200,)
depth filter done.
dangling removal done
color filter done.
12
(307200,)
depth filter done.
dangling removal done
color filter done.
13
(307200,)
depth filter done.
dangling removal done
color filter done.
14
(307200,)
depth filter done.
dangling removal done
color 

In [3]:
# load heads
all_heads=[HEAD_RECON.threeD_head.load_from_pickle(4,i) for i in range (1,16)]

In [4]:
def make_mhead(all_heads, first, last):
    all_heads[first].paint([1,0,0])
    all_heads[first].reset_positions()
    all_heads[first].reset_colors()
    all_heads[first+1].reset_positions()
    all_heads[first+1].reset_colors()    
    
    heads = multi_head.MultiHead.joined_heads(all_heads[first], all_heads[first+1])
#     heads.icp_transform(0,1)
    for i in range(first+2,last+1):
        all_heads[i].reset_positions()
        all_heads[i].reset_colors()  
        print (i)
        heads.append_head(all_heads[i])
        heads.join_heads_wraper(i-1-first,i-first)
#         heads.icp_transform(i-1-first,i-first)
    heads.save(sparcity=1) 
    print ("completed")
    return heads

In [5]:
heads = make_mhead(all_heads,0,14)

463



2


363




0 min_error True params: [ 0.02 14.    0.5 ]
363



3


230




0 min_error True params: [ 0.02 14.    0.5 ]
230



4


160


/Users/caseliang/Repositories/AV_CW/SIFT.py:62: RuntimeWarning: divide by zero encountered in double_scalars
  err = np.sqrt(np.var(dist) / (np.sum(inliers) - min_num_inliers))




0 min_error True params: [ 0.02 14.    0.5 ]
160



5


201




0 min_error True params: [ 0.02 14.    0.5 ]
201



6


207




0 min_error True params: [ 0.02 14.    0.5 ]
207



7


161




0 min_error True params: [ 0.02 14.    0.5 ]
161



8


111




0 min_error True params: [ 0.02 14.    0.5 ]
111



9


135




0 min_error True params: [ 0.02 14.    0.5 ]
135



10


106




0 min_error True params: [ 0.02 14.    0.5 ]
106



11


166




0 min_error True params: [ 0.02 14.    0.5 ]
166



12


204




0 min_error True params: [ 0.02 14.    0.5 ]
204



13


167




0 min_error True params: [ 0.02 14.    0.5 ]
167



14


301




0 min_error True params: [ 0.02 14.    0.5 ]
301



Saving Completed
completed


In [5]:
heads.left_eye_deviation(0)

0 172576
coordinate of the left eye: [ 0.0345545  -0.17854231 -0.02274339] in frame 0
1 172581
coordinate of the left eye: [ 0.03640054 -0.17906708 -0.01864559] in frame 1
12 169336
coordinate of the left eye: [ 0.0423335  -0.15481534  0.03370858] in frame 12
13 170000
coordinate of the left eye: [ 0.03882328 -0.1541353   0.03081354] in frame 13
14 169380
coordinate of the left eye: [ 0.03710537 -0.15637763  0.03361353] in frame 14
[ 0.03784344 -0.16458753  0.01134933]
[[-0.00328894 -0.01395478 -0.03409273]
 [-0.0014429  -0.01447955 -0.02999493]
 [ 0.00449006  0.00977219  0.02235924]
 [ 0.00097984  0.01045223  0.01946421]
 [-0.00073807  0.0082099   0.0222642 ]]
mean coordinate: [ 0.03784344 -0.16458753  0.01134933]. Distance to each points: [0.03698468 0.03333819 0.02481113 0.02211481 0.02374114].


(array([ 0.03784344, -0.16458753,  0.01134933]),
 array([0.03698468, 0.03333819, 0.02481113, 0.02211481, 0.02374114]))

In [9]:
heads.left_eye_deviation(1)

0 153974
coordinate of the left eye: [ 0.01958677 -0.12910025 -0.00640524] in frame 0
1 150143
coordinate of the left eye: [ 0.02184315 -0.12885785 -0.00816567] in frame 1
2 150124
coordinate of the left eye: [ 0.01827939 -0.12761078 -0.01151653] in frame 2
13 147576
coordinate of the left eye: [-0.00435965 -0.13210005 -0.00961363] in frame 13
14 150775
coordinate of the left eye: [-0.00726736 -0.12949743 -0.01545459] in frame 14
[ 0.00961646 -0.12943327 -0.01023113]
[[ 9.97031059e-03  3.33022414e-04  3.82588835e-03]
 [ 1.22266925e-02  5.75420423e-04  2.06546226e-03]
 [ 8.66292738e-03  1.82249184e-03 -1.28539527e-03]
 [-1.39761117e-02 -2.66677491e-03  6.17499115e-04]
 [-1.68838187e-02 -6.41597689e-05 -5.22345446e-03]]
mean coordinate: [ 0.00961646 -0.12943327 -0.01023113]. Distance to each points: [0.01068435 0.01241327 0.00894539 0.01424165 0.01767348].


(array([ 0.00961646, -0.12943327, -0.01023113]),
 array([0.01068435, 0.01241327, 0.00894539, 0.01424165, 0.01767348]))

In [13]:
heads.left_eye_deviation(2)

0 152103
coordinate of the left eye: [ 0.0477391  -0.16602056  0.00701409] in frame 0
1 152745
coordinate of the left eye: [ 0.05224443 -0.16629774  0.0119082 ] in frame 1
12 150113
coordinate of the left eye: [ 0.08484852 -0.13831299  0.12609314] in frame 12
13 149516
coordinate of the left eye: [ 0.0773928  -0.14083417  0.13746829] in frame 13
14 151469
coordinate of the left eye: [ 0.07982782 -0.13955872  0.13644406] in frame 14
[ 0.06841054 -0.15020484  0.08378556]
[[-0.02067143 -0.01581572 -0.07677146]
 [-0.01616611 -0.01609291 -0.07187736]
 [ 0.01643798  0.01189185  0.04230758]
 [ 0.00898227  0.00937066  0.05368274]
 [ 0.01141729  0.01064612  0.0526585 ]]
mean coordinate: [ 0.06841054 -0.15020484  0.08378556]. Distance to each points: [0.08106357 0.07541007 0.04692073 0.05522976 0.05492369].


(array([ 0.06841054, -0.15020484,  0.08378556]),
 array([0.08106357, 0.07541007, 0.04692073, 0.05522976, 0.05492369]))

In [6]:
heads.left_eye_deviation(3)

0 116190


IndexError: index 116190 is out of bounds for axis 0 with size 70610

In [30]:
a=np.empty((0,3))

In [32]:
a=np.append(a,np.array([1,1,1]))

In [33]:
a=np.stack((a,np.array([1,1,1])))

In [35]:
a=[]

In [38]:
a.append([1])

In [39]:
a

[[1], [1]]